runtime: python39  # Tidak menjalankan Python, hanya sebagai placeholder
instance_class: F1  # Kelas instance terendah

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"
