steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

# Optional: bisa tentukan project dan region jika perlu
# options:
#   logging: CLOUD_LOGGING_ONLY

timeout: '900s'  # 15 menit
