steps:
  # Step: Deploy langsung ke App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    dir: '.'

options:
  logging: CLOUD_LOGGING_ONLY
